version: '3.9'

services:
  dev:
    image: front:dev
    container_name: front_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm run dev

  prod:
    image: front:prod
    container_name: front_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm run build

  test:
    image: front:test
    container_name: front_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm run test