version: '3.9'

services:
  dev:
    image: front:dev
    container_name: front_dev
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"

  prod:
    image: front:prod
    container_name: front_prod
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build
    ports:
      - "8080:8080"

  test:
    image: front:test
    container_name: front_test
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test
    ports:
      - "8080:8080"