services:
  postgres_db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - tsd-net
  nest_backend:
    container_name: nest
    image: backend_image
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres_db
    networks:
      - tsd-net

networks:
  tsd-net:

volumes:
  pgdata:
